config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :product_images

  accepts_nested_attributes_for :product_images


end
	

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  
  belongs_to :product

  has_attached_file :picture, :styles => {:large => "600x600", :medium => "300x300>", :thumb => "150x150>" }
  
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end
# kode kubid

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    # 'desc' atau descending = diurutkan dari yg akhir ke awal. Z - A / paling lama dulu baru ke yg baru
    #  ascending atau ascending = diurutkan dari yg awal ke akhir. A - Z / paling baru dulu baru ke yg lama

    if params[:urutkan] == "nama" 
      products = Product.order('name asc') 
    elsif params[:urutkan] == "tanggal"
      products = Product.order('created_at desc')
    else
      products = Product.all
    end

    @keyword = params[:filter][:name] if params[:filter].present?
    if @keyword.present?
      @products = products.paginate(:page => params[:page], :per_page => 5).where("name LIKE ?", "%#{@keyword}%")
    else
      @products = products.paginate(:page => params[:page], :per_page => 5)
    end

    
  end
  
  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    3.times.each do |t|
      @product.product_images.new
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, product_images_attributes: :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Product Information</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class = "col-md-8 col-md-offset-2">
<body>
<%= yield %>
</div>
</body>

</html>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
    <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  
    <div class="control-group">
      <%= f.label :image, :class => 'control-label' %>
      <%= f.fields_for :product_images do |fpi| %>
        <div class="controls">
          <%= fpi.file_field :picture, :class => 'form-control' %>
        </div>
      <% end %>
      <%#= error_span(@product[:image]) %>
    </div>
  

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:name]) %>
  </div>

  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:price]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            products_path, :class => 'btn btn-default' %>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsable-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SUKABUMI PRODUCT INFO", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapsable-1">
        <ul class="nav navbar-nav">
            <% if user_signed_in? %>
            <li><%= link_to "New Product", new_product_path %></li>
            <li><%= link_to "Account", edit_user_registration_path %></li>
            <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
            <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
            <% end %>
        </ul>
      
        <form class="navbar-form navbar-collapse " role="search">
          <%- model_class = Product -%>
          <%= form_for :filter, :html => { :class => "form-horizontal product", method: :get } do |f| %>
            <div>
              <%=   f.text_field :name, value: @keyword, :class => "form-control" %>
              <%= f.submit "Search", class: "btn btn-success" %>
            </div>
          <% end -%>
      </form>
    </div>    
   </div> 
</nav>


<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= will_paginate @products, renderer: BootstrapPagination::Rails %>

<%= form_tag '/', method: :get do%>
  <%= select_tag 'urutkan', options_for_select([['Urutkan berdasarkan nama', 'nama'], ['Urutkan berdasarkan tanggal', 'tanggal']], 'nama')%>
  <%= submit_tag 'submit', class: "btn btn-sm btn-primary"%>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody> 
     <%  @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price, precision: 0, unit: "Rp. ") %></td>
        <td><%= product.created_at.strftime("%d %b %y, %H:%M") %></td>
        <% if product.product_images.present? %>
          <td><%= link_to image_tag(product.product_images.first.picture.url(:thumb)), product_path(product)  %></td>
        <% else %>
          <td>Tidak ada gambar</td>
        <% end %>
          

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1>Product Detail Information</h1>
</div>

<dl class="dl-horizontal">

  <dd><%= image_tag @product.product_images.first.picture.url(:large) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>